#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	local enabled
	config_load 5echarging
	config_get enabled global enabled 0
	[ "$enabled" = "1" ] || return 0

	/usr/bin/5echarging-uci2json

	procd_open_instance
	procd_set_param command /usr/bin/5echarging -config /var/etc/5echarging.json
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "5echarging"
}

reload_service() {
	stop
	start
}
